# Book settings
title: Learning from data
author: Dick Furnstahl
logo: ./_images/8820_icon.png

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    bibtex_reference_style: label
    bibtex_default_style: 'alpha'    
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    mathjax_config:
      TeX:
        Macros:
          "N": ["\\mathbb{N}"]
          "Z": ["\\mathbb{Z}"]
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat" : ["\\left[\\begin{array}"]
          "emat" : ["\\end{array}\\right]"]
          "thetavec": ["\\boldsymbol{\\theta}"]
          "Lra" : ["\\Longrightarrow"]



execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["_static/*","README.md","_slides/*","experiments/*"]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'


# Parse and render settings
parse:
  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links
  myst_enable_extensions    : ["dollarmath", "amsmath", "deflist", "colon_fence", "html_admonition","html_image", "linkify", "replacements", "smartquotes", "substitution"] # , "tasklist" ]

# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'

bibtex_bibfiles             : ["./references.bib"]

#######################################################################################
# Launch button settings
launch_buttons:
  colab_url                 : "https://colab.research.google.com"
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)

repository:
#  url                       : https://furnstahl.github.io/Physics-8820/LectureNotes/_build/html/index.html  # The URL to your book's repository
  url                       : https://github.com/furnstahl/Physics-8820  # The URL to your book's repository
  path_to_book              : "./LectureNotes"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links